Initial version release
commercetools/orders-update pull request #1
Opened 2016-11-30 09:05 UTC by Siilwyn

Release first version of this module.

- Tests
    - [ ] Unit
    - [ ] Integration
- [ ] Documentation
- [ ] Release on npm

2016-12-02 14:09 UTC, Siilwyn commented
@hisabimbola if you could already take a look at this, that would be great.
Note that the test is supposed to fail because of the integration test. :)

2016-12-07 15:14 UTC, Siilwyn commented
@hisabimbola so everything seems to be like I expect but no changes are made to the lineItems at the platform. :/
You'll need to build the SDK and use that in the modules: https://github.com/sphereio/sphere-node-sdk/pull/192  to try it out

2016-12-09 14:29 UTC, hisabimbola submitted a review, later dismissed
Added some comments.

Great work so far though 😎

2016-12-09 14:29 UTC, hisabimbola commented on src/orders-update.js
> +    return Promise.reject(validatedOrderData.errors)
Looking at the statement on line [38](https://github.com/commercetools/orders-update/pull/1/files#diff-f332f7d0a074668489505c96b5eae918R38), I am not sure this line will ever be evaluate since the error is in the response itself

2016-12-09 14:29 UTC, hisabimbola commented on package.json
>      "eslint-config-commercetools": "^4.0.0",
Since this is a new version, can we update to the new [`eslint-config-commercetools`](https://www.npmjs.com/package/eslint-config-commercetools) module?

2016-12-09 14:29 UTC, hisabimbola commented on readme.md
> +npm install @commercetools/orders-update --save-dev
why `save-dev`?

2016-12-09 14:29 UTC, hisabimbola commented on readme.md
> +    console.log(ordersUpdate.summary);
Can we make `ordersUpdate.summary` to be a method, so te summary report  can be flushed. Helpful, if the same instance of a class if been called several times.

2016-12-09 14:29 UTC, hisabimbola commented on src/get-api-credentials.js
> +import { ProjectCredentialsConfig } from 'sphere-node-utils'
This file is been used in almost all our modules now... we really should think of how to refactor it.

2016-12-09 14:29 UTC, hisabimbola commented on src/get-api-credentials.js
> +import Promise from 'bluebird'
Any reason for using `bluebird` or copy and paste 😉 😜

2016-12-09 14:29 UTC, hisabimbola commented on src/orders-update.js
> +  summaryReport () {
I added some comments on resetting, summary after it's called above

2016-12-09 14:29 UTC, hisabimbola commented on src/orders-update.js
> +      .then(this.updateOrder.bind(this))
why are you binding this?

2016-12-09 14:29 UTC, hisabimbola commented on src/orders-update.js
> +      .then(this.updateOrder.bind(this))
whether more explicit if you use arrow function for this ( => )

2016-12-09 14:29 UTC, hisabimbola commented on src/orders-update.js
> +        if (total > 0) {
Instead of checking if greater than 0, I think it's more clearer we check if it's equal to 1.

2016-12-09 14:29 UTC, hisabimbola commented on tests/integration/orders-update.spec.js
> +    .then(() => deleteAllApiItems(ordersUpdate.client, 'orders'))
Can we refactor this setup and teardown file to another method, that will be called here

2016-12-09 14:29 UTC, hisabimbola commented on tests/integration/orders-update.spec.js
> +    .then(() => deleteAllApiItems(ordersUpdate.client, 'orders'))
Good if we want to have another test suite in this file.

Best approach would have been to have a `before`/`after` API

2016-12-09 14:29 UTC, hisabimbola commented on tests/unit/get-api-credentials.spec.js
> +import getApiCredentials from 'get-api-credentials'
This also is a copy and paste test 😜 👿

2016-12-09 14:29 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +const PROJECT_KEY =
`CM_PROJECT_KEY`?

2016-12-09 14:29 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +    .catch(() => t.end())
We should check for the proper error message because anything can make it to fail.

2016-12-09 14:29 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +  should exist, needed for compatibility with the CLI`, (t) => {
👌

2016-12-09 14:32 UTC, hisabimbola commented
Meanwhile, I think 12 files changes is too much for just one commit. We should commit some changes regularly.

2016-12-09 14:36 UTC, Siilwyn commented on src/orders-update.js
> +      .then(this.updateOrder.bind(this))
Don't you think binding is more explicit? Feel like using an arrow function is implicit.

2016-12-09 14:38 UTC, Siilwyn commented on readme.md
> +npm install @commercetools/orders-update --save-dev
Yeah that doesn't make any sense. I blame copying from https://github.com/sphereio/sphere-product-type-import/#direct-usage
🍐

2016-12-09 14:40 UTC, Siilwyn commented on tests/unit/orders-update.spec.js
> +const PROJECT_KEY =
Getting rid of sphere branding but I think `COMMERCETOOLS_PROJECT_KEY` is a tad long.

2016-12-14 16:24 UTC, Siilwyn commented
@hisabimbola tests are finally passing! :3

2016-12-15 14:16 UTC, hisabimbola requested changes
We almost there, few comments added and hopefully we get the magic in the validated method 🤔

2016-12-15 14:16 UTC, hisabimbola commented on package.json
> +  "main": "dist/orders-update.js",
Let's change this to `lib`

2016-12-15 14:16 UTC, hisabimbola commented on package.json
>  {
We should add the authors fields...

2016-12-15 14:16 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +  sinon.stub(importer, 'processOrder', mockProcessOrder)
var spy = sinon.stub(importer, 'processOrder')

expect(spy.callCount).toBe(orders.length)

2016-12-15 14:16 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +        mockProcessOrder.callCount, orders.length,
Add `orders.length` to another line

2016-12-15 15:04 UTC, hisabimbola commented on package.json
>  {
Can we add the `prepublish` command?

2016-12-15 16:51 UTC, Siilwyn commented on package.json
> +  "main": "dist/orders-update.js",
Prefer `dist`, more obvious naming I think.

Currently our tools seem to use `dist` or `lib` pretty 50/50, so we can decide which to go with from now on:
- https://github.com/sphereio/sphere-node-cli/blob/master/package.json#L24
- https://github.com/sphereio/sphere-product-type-export/blob/master/package.json#L5
- https://github.com/sphereio/sphere-category-sync/blob/master/package.json#L27
- https://github.com/sphereio/sphere-stock-import/blob/master/package.json#L33
- https://github.com/sphereio/sphere-product-type-import/blob/master/package.json#L5
- https://github.com/sphereio/sphere-order-export/blob/master/package.json#L42

2016-12-16 08:54 UTC, Siilwyn commented
@hisabimbola realised `customLineItem` was missing, besides adding it I refactored the action building out of the main file. Review please! Danke schon! :)

2016-12-20 06:27 UTC, hisabimbola commented on src/orders-update.js
> +    const getStateReference = key => bluebird.props({
You need to check if the state object is present or not. Some times the object can be fully present (e.g from an API call), we don't want to do anything in that scenario.

2016-12-20 06:28 UTC, hisabimbola commented on tests/integration/orders-update.spec.js
> +          // TODO: use results instead of hardcoding
I don't quite get this comment...

2016-12-20 06:29 UTC, hisabimbola commented on tests/unit/build-order-actions.spec.js
> +test.skip('refactor!', (t) => {
still in progress I guess 👍

2016-12-20 11:22 UTC, Siilwyn commented on tests/integration/orders-update.spec.js
> +          // TODO: use results instead of hardcoding
changed

2016-12-20 11:22 UTC, Siilwyn commented on tests/unit/build-order-actions.spec.js
> +test.skip('refactor!', (t) => {
done

2016-12-20 13:50 UTC, Siilwyn commented on src/orders-update.js
> +    const getStateReference = key => bluebird.props({
Good addition. We can check against a schema with ajv to make sure or just they key names? Also maybe this can be done after releasing the first version?

2016-12-22 10:48 UTC, hisabimbola approved these changes

2016-12-22 10:48 UTC, merged