feat(orderUpdated): Add support for delivery methods
commercetools/orders-update pull request #15
Opened 2017-04-07 13:46 UTC by junajan

#### Summary
This PR resolves #14 

#### Description
It adds a support for actions `addDelivery` and `addParcelToDelivery`

#### Reviewers

- [ ] Reviewer 1 has approved the PR
- [ ] Reviewer 2 has approved the PR

#### TODO

- Tests
    - [x] Unit
    - [x] Integration
    - [ ] Acceptance
- [ ] Documentation

2017-04-10 15:12 UTC, adnasa approved these changes
This looks to me codewise 👍

2017-04-20 10:30 UTC, wizzy25 requested changes
Looks good... Just a few things I noticed

2017-04-20 10:30 UTC, wizzy25 commented on src/build-order-actions.js
> +    order = _.defaults(order, {
Why are you reassigning the parameter? You could have used a new variable entirely.

```js
    const modOrder = { shippingInfo: { deliveries: [] }, ...order }
    const modExistOrder = { shippingInfo: { deliveries: [] }, ...existingOrder }
```
And then you wouldn't need underscore here ;)

2017-04-21 09:48 UTC, hisabimbola commented
Let's keep this on hold till when it's implemented in the `csv-parser-order` module...

2017-05-18 07:57 UTC, junajan commented
There was added this PR https://github.com/commercetools/csv-parser-orders/pull/18 which adds a possibility to parse deliveries CSV into JSON object. This JSON object can be then taken by this module and imported into API.

2017-05-19 07:14 UTC, junajan commented on src/build-order-actions.js
> +    order = _.defaults(order, {
Simply beautiful .. thanks, updated here f84a39e

2017-05-22 14:42 UTC, junajan commented
This PR is currently blocked by this issue on the SDK https://github.com/sphereio/sphere-node-sdk/issues/229

2017-05-22 15:01 UTC, wizzy25 approved these changes

2017-05-23 13:33 UTC, hisabimbola approved these changes

2017-05-23 13:41 UTC, merged