fix(state-reference): module breaks when result count is 0
commercetools/orders-update pull request #3
Opened 2016-12-23 10:25 UTC by hisabimbola

fixes #2

#### Summary

#### Description

#### Reviewers

- [ ] Reviewer 1 has approved the PR
- [ ] Reviewer 2 has approved the PR

#### TODO

- Tests
    - [ ] Unit
    - [ ] Integration
    - [ ] Acceptance
- [ ] Documentation

2017-01-05 20:42 UTC, adnasa requested changes
without fully understanding the full context of the change, it looks good to me.

one minor change request though

2017-01-05 20:42 UTC, adnasa commented on tests/unit/orders-update.spec.js
> +      'Error message is descriptive')
new line on `)`

2017-01-09 11:25 UTC, Siilwyn commented
Instead of doing an `if - else`, serialise the error so the stack and all stays intact.

☝️  Before merging the commits should be squashed.

2017-01-10 09:10 UTC, Siilwyn commented
@hisabimbola please review. GH won't let me assign you since you opened the PR.

2017-01-10 09:18 UTC, hisabimbola reviewed
Lool, I can't approve or request changes on my own PR, but I added come comments

Aside those, the PR looks fine and good to go :1st_place_medal:

2017-01-10 09:18 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +    t.ok(result)
We should delete all that is in the `.then` since we expect it to fail

2017-01-10 09:18 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +    t.ok(error)
Add an assertion message, like line 303

2017-01-10 09:22 UTC, Siilwyn commented on tests/unit/orders-update.spec.js
> +    t.ok(result)
You realize that's your own code right? ^^

2017-01-10 09:26 UTC, hisabimbola commented on tests/unit/orders-update.spec.js
> +    t.ok(result)
😋

2017-01-10 09:30 UTC, Siilwyn commented on tests/unit/orders-update.spec.js
> +    t.ok(error)
Just removed the `t.ok` checks since the test will fail any way if the data does not exist.

2017-01-12 11:33 UTC, merged